# Generated by Django 4.2.5 on 2023-10-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_draft_advertisement_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='draft',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('DRAFT', 'Черновик')], default='DRAFT'),
        ),
    ]
