# Generated by Django 4.2.5 on 2023-10-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_tag_options_alter_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Раздел'),
        ),
    ]
